name: My Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Invoke workflow from another repository
      uses: RekhuGopal/InvokeGitHubActionsCalled/.github/workflows/calledworkflow.yml
      with:
        # Optional: Pass inputs to the workflow
        input_1: value_1
        input_2: value_2
